(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.ExcuseBusterCore = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const TRIGGERS = {
    fatigue: ['tired', 'sleep', 'exhausted', 'drained', 'bed', 'rest', 'late', 'night', 'nap'], time: ['busy', 'time', 'tomorrow', 'later', 'schedule', 'monday', 'next week'], motivation: ['motivation', 'feel like', 'mood', 'bored', 'vibe', 'lazy', 'feeling'], overwhelmed: ['overwhelmed', 'big', 'hard', 'difficult', 'confused', 'how', 'start', 'where', 'lost'], finance: ['money', 'pay', 'bill', 'cost', 'buy', 'expensive', 'finance', 'budget'], coding: ['code', 'program', 'project', 'write', 'learn', 'developer', 'repo', 'bug'], study: ['study', 'book', 'read', 'math', 'exam', 'homework', 'assignment', 'school', 'paper', 'essay', 'test'], gym: ['gym', 'workout', 'exercise', 'run', 'fit', 'sport', 'cardio', 'walk', 'jog', 'hike', 'step', 'stroll'], clean: ['clean', 'room', 'wash', 'dishes', 'chore', 'laundry', 'vacuum', 'tidy']
  };
  const ADVICE = { fatigue: 'Energy is your recurring trigger. Lower the bar: choose a two-minute starter and schedule demanding work for your most alert window.', time: 'Time scarcity keeps showing up. Protect one five-minute appointment today before planning the perfect future schedule.', motivation: 'Motivation is the pattern. Make the first move automatic: set out the tool, open the file, or start a two-minute timer before deciding how you feel.', overwhelmed: 'Task size is the pattern. Define the next visible action—not the whole project—then stop when the timer ends if you need to.', finance: 'Cost is the recurring blocker. Separate the no-cost first step from the purchase decision so progress does not wait on spending.', coding: 'Starting technical work is the recurring friction. Open the repo and write one failing test, TODO, or tiny function before researching further.', study: 'Study avoidance is recurring. Start with one question or one paragraph, with your phone out of reach, before you assess the full workload.', gym: 'Movement is the repeated hurdle. Commit only to shoes on and five minutes of movement; consistency comes before intensity.', clean: 'Chores are the recurring drag. Pick one surface or three items and finish that micro-zone before choosing another task.', generic: 'Your pattern is delay itself. Make the next action so small that it is harder to negotiate with than to complete.' };
  function classifyExcuse(text) { const value = String(text || '').toLowerCase(); const scored = Object.entries(TRIGGERS).map(([trigger, terms]) => [trigger, terms.reduce((score, term) => score + (value.includes(term) ? term.split(' ').length : 0), 0)]); const best = scored.reduce((winner, current) => current[1] > winner[1] ? current : winner, ['generic', 0]); return best[1] ? best[0] : 'generic'; }
  function getPersonalizedAdvice(history) { const counts = (history || []).reduce((all, item) => { const trigger = item.category || classifyExcuse(item.excuse); all[trigger] = (all[trigger] || 0) + 1; return all; }, {}); const [trigger = 'generic', occurrences = 0] = Object.entries(counts).sort((a, b) => b[1] - a[1])[0] || []; return { trigger, occurrences, message: ADVICE[trigger] || ADVICE.generic }; }
  function normalizeResponse(payload, roadmapMode) { if (!payload || typeof payload !== 'object') throw new Error('The coach returned an unreadable response.'); const rawSteps = payload.action_steps || payload.action; const steps = (Array.isArray(rawSteps) ? rawSteps : [rawSteps]).filter(step => typeof step === 'string' && step.trim()).map(step => step.trim()).slice(0, roadmapMode ? 3 : 1); if (!payload.real_excuse && !payload.excuse) throw new Error('The coach response did not identify the procrastination trigger.'); if (!payload.callout || !steps.length) throw new Error('The coach response was incomplete.'); return { real_excuse: String(payload.real_excuse || payload.excuse).trim(), callout: String(payload.callout).trim(), action_title: String(payload.action_title || (roadmapMode ? '3-STEP HABIT ROADMAP' : '5-MINUTE ACTION')).trim(), action_steps: steps }; }
  async function requestJson(url, options, fetchImpl, timeoutMs = 12000) { const controller = typeof AbortController === 'undefined' ? null : new AbortController(); const timer = controller ? setTimeout(() => controller.abort(), timeoutMs) : null; try { const response = await fetchImpl(url, { ...options, signal: controller ? controller.signal : undefined }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message || `Request failed (${response.status}).`); return body; } catch (error) { if (error && error.name === 'AbortError') throw new Error('The coach request timed out. Your local coach is ready instead.'); throw error; } finally { if (timer) clearTimeout(timer); } }
  function createResponseOrchestrator({ remote, fallback }) { return async input => { try { return { response: normalizeResponse(await remote(input), input.roadmapMode), source: 'ai' }; } catch (error) { return { response: normalizeResponse(fallback(input), input.roadmapMode), source: 'local', error }; } }; }
  return { classifyExcuse, getPersonalizedAdvice, normalizeResponse, requestJson, createResponseOrchestrator };
});
